# yaml-language-server: $schema=https://raw.githubusercontent.com/GoogleContainerTools/skaffold/main/docs/content/en/schemas/v2beta23.json
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: zuzi-site

build:
  local:
    useBuildkit: true
  artifacts:
    - image: zevisert/zuzi-site
      context: site
      docker:
        dockerfile: site/Dockerfile
        target: runner
      sync:
        # Sync is only applicable in dev
        manual:
          - src: src/**/*.{js,ts,tsx,css}
            dest: /site/
          - src: public/**/*
            dest: /site/

deploy:
  kubectl:
    defaultNamespace: zuzi-staging
    manifests:
      - k8s/environments/staging/namespace.yaml
      - k8s/environments/staging/env.secret.yaml
      - k8s/environments/staging/ingress.yaml
      - k8s/http.service.yaml
      - k8s/next.deployment.yaml
      - k8s/postgres.yaml
    hooks: {}

portForward:
  - resourceType: service
    resourceName: db-primary
    namespace: zuzi-dev # Applicable only to dev/debug anyway
    localPort: 5432
    port: postgres

profiles:
  - activation:
      - command: dev
        kubeContext: docker-desktop
      - command: debug
        kubeContext: docker-desktop
    name: dev

    patches:
      # Set the namespace to zuzi-dev
      - op: replace
        path: /deploy/kubectl/defaultNamespace
        value: zuzi-dev

      # Docker build target is the dev image
      - op: replace
        path: /build/artifacts/0/docker/target
        value: dev-server

      # Use the dev namespace manifest
      - op: replace
        path: /deploy/kubectl/manifests/0
        value: k8s/environments/dev/namespace.yaml

      # Use the dev secrets manifest
      - op: replace
        path: /deploy/kubectl/manifests/1
        value: k8s/environments/dev/env.secret.yaml

      # Use the dev ingress manifest
      - op: replace
        path: /deploy/kubectl/manifests/2
        value: k8s/environments/dev/ingress.yaml

  - name: prod
    patches:
      # Set the prod namespace to zuzi-site
      - op: replace
        path: /deploy/kubectl/defaultNamespace
        value: zuzi-site

        # Target the prod config
      - op: replace
        path: /deploy/kubectl/manifests/0
        value: k8s/environments/prod/namespace.yaml

        # Target the prod config
      - op: replace
        path: /deploy/kubectl/manifests/1
        value: k8s/environments/prod/env.secret.yaml

        # Target the prod config
      - op: replace
        path: /deploy/kubectl/manifests/2
        value: k8s/environments/prod/ingress.yaml
