apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: zuzi-site

build:
  local:
    useBuildkit: true
  artifacts:
  - image: zevisert/zuzi-site-frontend
    docker:
      dockerfile: src/Dockerfile
      target: prpl
    sync: {}
  - image: zevisert/zuzi-site-server
    docker:
      dockerfile: server/Dockerfile

deploy:
  kubectl:
    defaultNamespace: zuzi-staging
    manifests:
    - k8s/staging/namespace.yaml
    - k8s/staging/env.secret.yaml
    - k8s/staging/ingress.yaml
    - k8s/api.service.yaml
    - k8s/http.service.yaml
    - k8s/server.deployment.yaml
    - k8s/frontend.deployment.yaml
    - k8s/mongodb.yaml

profiles:
  - name: dev
    patches:
        # Set the namespace to zuzi-dev
      - op: replace
        path: /deploy/kubectl/defaultNamespace
        value: zuzi-dev

        # Target the dev config
      - op: replace
        path: /deploy/kubectl/manifests/0
        value: k8s/dev/namespace.yaml

        # Target the dev config
      - op: replace
        path: /deploy/kubectl/manifests/1
        value: k8s/dev/env.secret.yaml
        
        # Target the dev config
      - op: replace
        path: /deploy/kubectl/manifests/2
        value: k8s/dev/ingress.yaml

        # Don't deploy mongo - using mlab here
      - op: remove
        path: /deploy/kubectl/manifests/7

        # Docker build target is the dev image
      - op: replace
        path: /build/artifacts/0/docker/target
        value: dev

        # Set sync config for fast reload 
      - op: replace
        path: /build/artifacts/0/sync
        value:
          manual:
            - src: src/**/*.js
              dest: /site/
            - src: images/**/*.png
              dest: /site/
            - src: images/**/*.jpg
              dest: /site
            - src: images/**/*.ico
              dest: /site/
    activation:
      - command: dev
        kubeContext: docker-desktop

  - name: prod
    patches:
      # Set the prod namespace to zuzi-site
      - op: replace
        path: /deploy/kubectl/defaultNamespace
        value: zuzi-site

        # Target the prod config
      - op: replace
        path: /deploy/kubectl/manifests/0
        value: k8s/prod/namespace.yaml

        # Target the prod config
      - op: replace
        path: /deploy/kubectl/manifests/1
        value: k8s/prod/env.secret.yaml
        
        # Target the prod config
      - op: replace
        path: /deploy/kubectl/manifests/2
        value: k8s/prod/ingress.yaml
