apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: zuzi-site
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - name: api
    port: 80
    protocol: TCP
    targetPort: 8080
