apiVersion: v1
kind: Service
metadata:
  labels:
    app: http
  name: http
  
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  
