apiVersion: v1
kind: Service
metadata:
  labels:
    app: http
  name: next

spec:
  type: ClusterIP
  selector:
    app: next
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
