apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb

spec:
  members: 2
  arbiters: 1
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      modes: 
        - SCRAM
  users:
    - name: koa
      db: admin
      passwordSecretRef:
        name: env
        key: MONGO_PW
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-scram
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: 200m
                  memory: 250M
                requests:
                  cpu: 200m
                  memory: 200M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: 200m
                  memory: 250M
                requests:
                  cpu: 200m
                  memory: 200M
