# npx @brpaz/crd-jsonschema-converter -c k8s/.schemas/schemas.yaml -o k8s/.schemas
crds:
  - name: postgres-operator
    sources:
      master:
        - https://raw.githubusercontent.com/CrunchyData/postgres-operator-examples/main/kustomize/install/bases/crd/bases/postgres-operator.crunchydata.com_postgresclusters.yaml
